services:
  server:
    image: jerichowalls/server:1.0.0
    container_name: datavault-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/datavault
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - datavault-network
  db:
    image: postgres:15
    container_name: datavault-server-db
    restart: always
    environment:
      POSTGRES_DB: datavault
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - datavault-data:/var/lib/postgresql/data
    networks:
      - datavault-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - datavault-network


  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    environment:
      - LDAP_ORGANISATION=DataVault
      - LDAP_DOMAIN=datavault.com
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ADMIN_USER=cn=admin,dc=datavault,dc=com
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ./users.ldif:/users.ldif

networks:
  datavault-network:
    driver: bridge


volumes:
  ldap-data:
  ldap-config:
  datavault-data:
  pgadmin-data:
  
    
